### ISSUE TITLE
ph5tostationxml.py starttime & endtime wildcards

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#10]
The starttime and endtime arguments in ph5tostationxml.py _need to accept_ the * wildcard. The ? wildcard _does not_ need to be supported though.

Also I'd suggest raising a custom exception when a invalid starttime or endtime is entered, instead of just allowing the code to break.

````
(venv) falco:apps nick$ python ph5tostationxml.py -n master.ph5 -p /hdf5-data2/PH5_Experiments/pn4/13-005/ --starttime=*

Traceback (most recent call last):
  File "ph5tostationxml.py", line 586, in <module>
    ph5sxml = PH5toStationXML(args_dict)
  File "ph5tostationxml.py", line 187, in __init__
    self.args.get('start_time'), "%Y:%j:%H:%M:%S.%f")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '*' does not match format '%Y:%j:%H:%M:%S.%f'
````

**Comment by nick-iris** [comment]
I've added support for this in the PH5 Station Service web handler. Basically I just ignore starttime and endtime when they are set to * in a http POST request, indicating that all dates were requested. * is still invalid for station service http GET requests.

Note that you should still probably catch invalid date entries in your code instead of allowing it to error out.
