### ISSUE TITLE
ph5view error

### ISSUE THREAD

**Issue by damhuonglan** [PIC-IRIS/PH5#186]
1. When reading SUGAR data set
/home/field/Desktop/SUGAR_PH5/Sigma/master.ph5
File "/home/field/PH5/ph5/clients/ph5view/ph5_viewer.py", line 3807, in onGetnPlot
    val = self.createVal()
  File "/home/field/PH5/ph5/clients/ph5view/ph5_viewer.py", line 4092, in createVal
    val = self.getPH5Data(orgStartT, self.offset, self.dfltTimeLen, staSpc )
  File "/home/field/PH5/ph5/clients/ph5view/ph5_viewer.py", line 4034, in getPH5Data
    ph5Valfile[:] = PH5Val[:]
ValueError: setting an array element with a sequence. 

2. When reading Mudbog data set
/storage/Mudbog/PH5/master.ph5
Traceback (most recent call last):
  File "/home/field/PH5/ph5/clients/ph5view/ph5_viewer.py", line 2905, in onFile
    PH5Object.createGraphExperiment()
  File "/home/field/PH5/ph5/clients/ph5view/ph5_viewer_reader.py", line 105, in createGraphExperiment
    self.graphExperiment = rows[-1]
IndexError: list index out of range

**Comment by derick-hess** [comment]
Closing this.  Those data sets on the internal server are old data sets and incomplete.
