### ISSUE TITLE
ph5toevt request results in unexpected error

### ISSUE THREAD

**Issue by nick-iris** [PIC-IRIS/PH5#280]
**Describe the bug**
I made a `ph5toevt` request that resulted in an unexpected error.

**To Reproduce**
`ph5toevt --path=/hdf5-data2/PH5_Experiments/pn4/15-016/ --nickname=master.ph5 --length=120 -A=001 --offset=0 --reduction_velocity=0 --eventnumber=5013 --shot_line=001`

results in the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/nick/anaconda/envs/ph5/bin/ph5toevt", line 11, in <module>
    load_entry_point('ph5', 'console_scripts', 'ph5toevt')()
  File "/Users/nick/Development/workspace/PH5/ph5/clients/ph5toevt.py", line 655, in main
    gather()
  File "/Users/nick/Development/workspace/PH5/ph5/clients/ph5toevt.py", line 270, in gather
    ARGS.station_array, evt, ARGS.shot_line)
  File "/Users/nick/Development/workspace/PH5/ph5/core/ph5api.py", line 419, in read_offsets_shot_order
    name=offset_table_name)
  File "/Users/nick/Development/workspace/PH5/ph5/core/experiment.py", line 364, in read_offset_fast
    ret['offset/value_d'],
KeyError: 'offset/value_d'
```

**Comment by derick-hess** [comment]
Thanks i'll fix this. That experiment must not have an offset table, but an offset table also shouldn't be required. I will give you a kef to fix that experiment, then update experiment to not fail adn return an empty table if it doesn't exist.

**Comment by derick-hess** [comment]
I'll also add a feature request to ph5_validate to check for this. IF there are shot lines then the offset table should be calculated and present in PH5

**Comment by derick-hess** [comment]
I have a fix. Running tests on all the data sets I have in house that have events to make sure. Should have the fix posted within an hour
