### ISSUE TITLE
[BUG] csvtokef fails with key error on file with 'UTF-8 with BOM' character encoding

### ISSUE THREAD

**Issue by Stephen-Veitch** [PIC-IRIS/PH5#536]
Attempting to convert a csv of an offset table from csv to kef when the encoding of the source file is 'UTF-8 with BOM' fails with the following error:

```(ph5) sveitch@picmbp meta % csvtokef -f offset_v20240802_sign_corrected.csv -o offset_v20240802_sign_corrected.kef
Traceback (most recent call last):
  File "/Users/sveitch/anaconda3/envs/ph5/bin/csvtokef", line 11, in <module>
    load_entry_point('ph5', 'console_scripts', 'csvtokef')()
  File "/Users/sveitch/Documents/code/ph5/PH5/ph5/utilities/csvtokef.py", line 45, in main
    keffile.write("{0}\n".format(kef_dict['table']))```

This operation will be successful with simple 'UTF-8' encoding.  Excel will write csvs with BOM encoding under certain circumstances (I don't know when/why) so this is an issue that may be likely to come up for other users.

**Comment by Stephen-Veitch** [comment]
[array_v0.utf8.csv](https://github.com/user-attachments/files/16911381/array_v0.utf8.csv)
[array_v0.utf8bom.csv](https://github.com/user-attachments/files/16911383/array_v0.utf8bom.csv)
